pub(crate) mod account;
pub(crate) mod commodity_value;
pub(crate) mod price;
pub(crate) mod transaction;
mod utils; // Private module for support functions and types

use std::io::Write;

/// A journal file handler that can read and write content of/to a journal file.
pub struct JournalFile {
    /// The path to the journal file.
    path: std::path::PathBuf,
}

impl JournalFile {
    /// Creates a new `JournalFile` instance with the given path.
    ///
    pub fn new(path: std::path::PathBuf) -> Self {
        Self { path }
    }

    /// Creates a new, empty, journal file at the specified path if one does not already exist.
    ///
    /// # Examples
    /// ```
    /// let mut journal_file = journalist::JournalFile::new("path/to/journal.journal");
    /// let result = journal_file.create();
    /// ```
    pub fn create(&self) -> crate::Result<()> {
        // Create the journal file if it doesn't exist
        if !self.path.exists() {
            if let Some(parent) = self.path.parent() {
                match std::fs::create_dir_all(parent) {
                    Ok(_) => (),
                    Err(e) => return Err(crate::error::RsledgerError::IoError(e)),
                }
            }

            match std::fs::File::create(&self.path) {
                Ok(_) => return Ok(()),
                Err(e) => return Err(crate::error::RsledgerError::IoError(e)),
            }
        }

        return Err(crate::error::RsledgerError::IoError(std::io::Error::new(
            std::io::ErrorKind::AlreadyExists,
            format!("Journal file {} already exists.", self.path.display()),
        )));
    }

    pub fn load(&mut self) -> crate::Result<Journal> {
        // TODO: Implement the logic to read the journal

        println!("Warning: Journal loading is not yet implemented. Returning an empty journal.");

        let transactions: Vec<transaction::Transaction> = Vec::new();
        let prices: Vec<price::PriceDirective> = Vec::new();

        return Ok(Journal::new(transactions, prices));
    }

    /// Adds an entry to the journal file.
    ///
    /// The entry can be any type that implements the `Display` trait, such as a transaction or a price directive.
    ///
    /// # Examples
    /// ```
    /// let mut journal_file = journalist::JournalFile::new("path/to/journal.journal");
    /// let transaction = types::transaction::Transaction::new(...);
    /// let result = journal_file.add_entry(&transaction);
    /// ```
    pub fn add_entry(&mut self, entry: &dyn std::fmt::Display) -> crate::Result<()> {
        // Open the file in append mode
        let mut file: std::fs::File =
            match std::fs::OpenOptions::new().append(true).open(&self.path) {
                Ok(f) => f,
                Err(e) => {
                    return Err(crate::error::RsledgerError::IoError(e));
                }
            };

        // Write the entry to file using its implemented Display trait
        match writeln!(file, "{entry}") {
            Ok(_) => return Ok(()),
            Err(e) => return Err(crate::error::RsledgerError::IoError(e)),
        };
    }
}

/// An in-memory representation of a journal.
///
/// Contains the transactions and prices that have been read from a journal file,
/// or generated by the application.
pub struct Journal {
    /// All transactions in the journal.
    pub transactions: Vec<transaction::Transaction>,
    /// All price directives in the journal.
    pub prices: Vec<price::PriceDirective>,
}

impl Journal {
    /// Creates a new journal with the given path. Counts the number of each type of directive
    /// in the journal but does not read the contents of the journal into memory.
    ///
    /// # Examples
    /// ```
    /// let journal = journalist::Journal::new("path/to/journal.journal");
    /// ```
    pub fn new(
        transactions: Vec<transaction::Transaction>,
        prices: Vec<price::PriceDirective>,
    ) -> Self {
        Self {
            transactions,
            prices,
        }
    }
}
