mod account;
mod commodity_value;
mod price;
mod transaction;

use std::io::Write;

/// A journal file handler that can read and write content of/to a journal file.
pub struct JournalFile {
    /// The path to the journal file.
    path: std::path::PathBuf,
    /// Number of each type of directive in the journal.
    directive_counts: std::collections::HashMap<DirectiveType, usize>,
}

impl JournalFile {
    pub fn new(path: std::path::PathBuf) -> Self {
        // TODO: Implement the logic to read the journal file and count the directives.

        Self {
            path,
            directive_counts: std::collections::HashMap::new(),
        }
    }

    pub fn load(&mut self) -> crate::Result<Journal> {
        // TODO: Implement the logic to read the journal

        println!("Warning: Journal loading is not yet implemented. Returning an empty journal.");

        let transactions: Vec<transaction::Transaction> = Vec::new();
        let prices: Vec<price::PriceDirective> = Vec::new();

        return Ok(Journal::new(transactions, prices));
    }

    /// Adds an entry to the journal file.
    ///
    /// The entry can be any type that implements the `Display` trait, such as a transaction or a price directive.
    ///
    /// # Examples
    /// ```
    /// let mut journal_file = journalist::JournalFile::new("path/to/journal.journal");
    /// let transaction = types::transaction::Transaction::new(...);
    /// let result = journal_file.add_entry(&transaction);
    /// ```
    pub fn add_entry(&mut self, entry: &dyn std::fmt::Display) -> crate::Result<()> {
        // Open the file in append mode
        let mut file: std::fs::File =
            match std::fs::OpenOptions::new().append(true).open(&self.path) {
                Ok(f) => f,
                Err(e) => {
                    return Err(crate::error::RsledgerError::IoError(e));
                }
            };

        // Write the entry to file using its implemented Display trait
        match writeln!(file, "{}", entry) {
            Ok(_) => return Ok(()),
            Err(e) => return Err(crate::error::RsledgerError::IoError(e)),
        };
    }
}

/// An in-memory representation of a journal.
///
/// Contains the transactions and prices that have been read from a journal file,
/// or generated by the application.
pub struct Journal {
    /// All transactions in the journal.
    pub transactions: Vec<transaction::Transaction>,
    /// All price directives in the journal.
    pub prices: Vec<price::PriceDirective>,
}

/// The types of directives that can be stored in a journal.
/// Limited support at the moment, needs to be expanded.
enum DirectiveType {
    /// For transactions.
    Transaction,
    /// For price directives.
    Price,
    /// For unrecognised directives.
    None,
}

impl Journal {
    /// Creates a new journal with the given path. Counts the number of each type of directive
    /// in the journal but does not read the contents of the journal into memory.
    ///
    /// # Examples
    /// ```
    /// let journal = journalist::Journal::new("path/to/journal.journal");
    /// ```
    pub fn new(
        transactions: Vec<transaction::Transaction>,
        prices: Vec<price::PriceDirective>,
    ) -> Self {
        Self {
            transactions,
            prices,
        }
    }
}
